---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Remove unofficial docker images"
  package:
    name: 
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  register: docker_remove  
  become: true
  become_method: sudo

- name: "Install XRDP"
  apt:
    name: xrdp
    state: present
  become: true
  become_method: sudo

- name: "Start XRDP Service"
  service:
    name: xrdp
    state: started
  become: true
  become_method: sudo

- name: "Enable XRDP Service"
  service:
    name: xrdp
    enabled: true
  become: true
  become_method: sudo

- name: "Add xrdp user to ssl-cert group"
  user:
    name: xrdp
    groups: ssl-cert
    append: yes
  become: true
  become_method: sudo

- name: "Install Desktop Environment"
  apt:
    name:
      - xfce4
      - xfce4-goodies
      - xorg
      - dbus-x11
      - x11-xserver-utils
    state: present
  become: true
  become_method: sudo

- name: "Install locate utility"
  apt:
    name:
      - mlocate
    state: present
  become: true
  become_method: sudo

# This is for https://github.com/lgandx/PCredz?tab=readme-ov-file
- name: "Install libpcap-dev"
  apt:
    name:
      - libpcap-dev
    state: present
  become: true
  become_method: sudo

- name: Update locate database
  command: updatedb
  changed_when: true
  become: true
  become_method: sudo

- name: "Add Docker keyring to apt"
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  become: true
  become_method: sudo

- name: "Install Docker Repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ distribution }} stable"
    state: present
    update_cache: yes
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Install Docker"
  package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true
  become_method: sudo
