---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Remove old root-installed creds symlink
  become: true
  file:
    path: /usr/local/bin/creds
    state: absent

- name: Ensure pipx is installed system-wide
  become: true
  apt:
    name: pipx
    state: present

- name: Ensure ~/.local/bin exists for user
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install defaultcreds-cheat-sheet as normal user
  command: pipx install --force defaultcreds-cheat-sheet
  become: false
  environment:
    HOME: "{{ ansible_env.HOME }}"
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Ensure ~/.local/bin is in PATH permanently
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    insertafter: EOF
