---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  apt:
    name: pipx
    state: present
  become: true

- name: Ensure pipx path is set up
  command: pipx ensurepath
  changed_when: false

- name: Install or upgrade defaultcreds-cheat-sheet with pipx (as normal user)
  command: pipx install --force defaultcreds-cheat-sheet
  register: pipx_install
  changed_when: "'installed package' in pipx_install.stdout or 'upgraded package' in pipx_install.stdout"

- name: Copy creds binary to /usr/local/bin for global access
  become: true
  copy:
    src: "{{ lookup('env','HOME') }}/.local/bin/creds"
    dest: /usr/local/bin/creds
    mode: '0755'
    remote_src: yes
