---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  become: true
  apt:
    name: pipx
    state: present

- name: Ensure pipx is usable by the current user
  become: true
  command: "python3 -m pipx ensurepath"
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Install defaultcreds-cheat-sheet via pipx
  become: false
  pip:
    name: defaultcreds-cheat-sheet
    executable: pipx
    state: present
    