---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  apt:
    name: pipx
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx path is set up
  command: pipx ensurepath
  changed_when: false

- name: Remove old root pipx venv
  become: true
  file:
    path: /root/.local/pipx/venvs/defaultcreds-cheat-sheet
    state: absent

- name: Install defaultcreds-cheat-sheet with pipx (as normal user)
  command: pipx install --force defaultcreds-cheat-sheet
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/defaultcreds-cheat-sheet"
