---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Remove old root-installed creds symlink
  become: true
  file:
    path: /usr/local/bin/creds
    state: absent

- name: Ensure pipx is installed system-wide
  become: true
  apt:
    name: pipx
    state: present

- name: Ensure pipx path is set up for the user
  command: pipx ensurepath
  changed_when: false
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install or upgrade defaultcreds-cheat-sheet for the user
  command: pipx install --force defaultcreds-cheat-sheet
  environment:
    PATH: "{{ ansible_env.PATH }}"
    HOME: "{{ ansible_env.HOME }}"

- name: Ensure ~/.local/bin is in PATH permanently
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    insertafter: EOF
