---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed system-wide
  become: true
  apt:
    name: pipx
    state: present

- name: Configure pipx for current user
  become: false
  shell: |
    python3 -m pipx ensurepath
    source ~/.bashrc
    pipx completions bash > ~/.local/share/bash-completion/completions/pipx
  args:
    executable: /bin/bash

- name: Install defaultcreds-cheat-sheet via pipx as normal user
  become: false
  shell: pipx install --force defaultcreds-cheat-sheet
  args:
    creates: "{{ ansible_env.HOME }}/.local/pipx/venvs/defaultcreds-cheat-sheet"

- name: Verify installation
  become: false
  shell: creds --version
  register: creds_version
  failed_when: creds_version.rc != 0
