---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed system-wide
  become: true
  apt:
    name: pipx
    state: present

- name: Ensure pipx is usable for normal user
  become: false
  shell: python3 -m pipx ensurepath
  args:
    executable: /bin/bash

- name: Install defaultcreds-cheat-sheet via pipx as normal user
  become: false
  shell: pipx install defaultcreds-cheat-sheet
  args:
    creates: "{{ ansible_env.HOME }}/.local/pipx/venvs/defaultcreds-cheat-sheet"
