---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Install pipx
  ansible.builtin.apt:
    name: pipx
    state: present

- name: Install defaultcreds-cheat-sheet
  ansible.builtin.command:
    cmd: pipx install defaultcreds-cheat-sheet
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/bin:/bin"

- name: Ensure pipx binaries are in PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: true

- name: Reload shell configuration
  ansible.builtin.shell:
    cmd: bash -c 'source ~/.bashrc'
  changed_when: false

- name: Verify installation
  ansible.builtin.command:
    cmd: creds --help
  register: creds_output
  failed_when: false

- name: Display verification result
  ansible.builtin.debug:
    msg: "{{ creds_output.stdout | default('Installation verification failed') }}"
