---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure python3-venv is installed
  apt:
    name: python3-venv
    state: present
  become: false
  # become_method: sudo

- name: Create virtualenv for tools
  command: python3 -m venv /opt/tools-venv
  args:
    creates: /opt/tools-venv/bin/activate
  become: false
  # become_method: sudo

- name: Install defaultcreds-cheat-sheet in venv
  pip:
    name: defaultcreds-cheat-sheet
    virtualenv: /opt/tools-venv
    virtualenv_command: python3 -m venv
  become: false
  # become_method: sudo
  
