---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  apt:
    name: pipx
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx path is set up
  command: pipx ensurepath
  changed_when: false

- name: Install defaultcreds-cheat-sheet with pipx (as normal user)
  command: pipx install --force defaultcreds-cheat-sheet
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/defaultcreds-cheat-sheet"

- name: Install pypykatz with pipx (as normal user)
  command: pipx install --force pypykatz
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/pypykatz"

- name: Install donpapi with pipx (as normal user)
  command: pipx install --force donpapi
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/donpapi"

- name: "Install krb5-user utility"
  apt:
    name:
      - krb5-user
    state: present
  become: true
  become_method: sudo

- name: Setup PKINITtools from script
  ansible.builtin.shell: |
    set -e
    git clone https://github.com/dirkjanm/PKINITtools.git
    cd PKINITtools
    python3 -m venv .PKINITtools
    source .PKINITtools/bin/activate
    pip3 install -r requirements.txt
    pip3 install -I git+https://github.com/wbond/oscrypto.git
  args:
    chdir: "{{ lookup('env','HOME') }}/.local/python/venvs/"
