---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  apt:
    name: pipx
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx path is set up
  command: pipx ensurepath
  changed_when: false

- name: Install defaultcreds-cheat-sheet with pipx (as normal user)
  command: pipx install --force defaultcreds-cheat-sheet
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/defaultcreds-cheat-sheet"

- name: Install pypykatz with pipx (as normal user)
  command: pipx install --force pypykatz
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/pypykatz"

- name: Install donpapi with pipx (as normal user)
  command: pipx install --force donpapi
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/donpapi"

- name: "Install krb5-user utility"
  apt:
    name:
      - krb5-user
    state: present
  become: true
  become_method: sudo

# - name: Install oscrypto with pipx (as normal user needed for PKINITtools)
#   command: pipx install git+https://github.com/wbond/oscrypto.git
#   become: false
#   args:
#     creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/oscrypto"

- name: Install oscrypto in virtual environment
  become: false  # Don't use sudo for virtual environment creation
  block:
    - name: Create virtual environment
      command:
        cmd: python3 -m venv oscrypto
        creates: "{{ lookup('env','HOME') }}/.local/python3/venvs/oscrypto"
      args:
        chdir: "{{ playbook_dir }}"  # Create in playbook directory

    - name: Activate virtual environment
      command:
        cmd: source myenv/bin/activate && python -c "import sys; print(sys.prefix)"
        creates: "{{ lookup('env','HOME') }}/.local/python3/venvs/oscrypto/venv_active.txt"  # Marker file to track activation
      args:
        chdir: "{{ playbook_dir }}"
      register: venv_activation
      failed_when: "'prefix' not in venv_activation.stdout"

    - name: Install oscrypto
      pip:
        name: git+https://github.com/wbond/oscrypto.git
        executable: pip3
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ lookup('env','HOME') }}/.local/python3/venvs/oscrypto/bin"
