---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx is installed
  apt:
    name: pipx
    state: present
  become: true
  become_method: sudo

- name: Ensure pipx path is set up
  command: pipx ensurepath
  changed_when: false

- name: Install defaultcreds-cheat-sheet with pipx (as normal user)
  command: pipx install --force defaultcreds-cheat-sheet
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/defaultcreds-cheat-sheet"

- name: Install pypykatz with pipx (as normal user)
  command: pipx install --force pypykatz
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/pypykatz"

- name: Install donpapi with pipx (as normal user)
  command: pipx install --force donpapi
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/donpapi"

# This is for https://github.com/lgandx/PCredz?tab=readme-ov-file
- name: Install Cython with pipx (as normal user)
  command: pipx install --force Cython
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/Cython"

# This is for https://github.com/lgandx/PCredz?tab=readme-ov-file
- name: Install python-libpcap with pipx (as normal user)
  command: pipx install --force python-libpcap
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/python-libpcap"

# This is for https://github.com/lgandx/PCredz?tab=readme-ov-file
- name: Install pylibpcap with pipx (as normal user)
  command: pipx install --force pylibpcap
  become: false
  args:
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/pylibpcap"

