---
- name: "Install dislocker utility"
  apt:
    name:
      - dislocker
    state: present
  become: true
  become_method: sudo

- name: "Install xfreerdp utility"
  apt:
    name:
      - freerdp2-x11
    state: present
  become: true
  become_method: sudo

- name: Install defaultcreds-cheat-sheet
  become: false
  pip:
    name: defaultcreds-cheat-sheet
    virtualenv: ~/.venvs/defaultcreds
    executable: pip3
