---
- name: Create directory for windows tools
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/tools/windows"
    state: directory

- name: Download LaZagne.exe and save to tools folder
  ansible.builtin.get_url:
    url: https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.7/LaZagne.exe
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/LaZagne.exe"
    mode: '0755'

- name: Copy mimikatz.exe tools directory
  local_action:
    module: copy
    src: "/usr/share/windows-resources/mimikatz/x64/mimikatz.exe"
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/mimikatz.exe"
    mode: '0755'

- name: Copy kerbrute_linux_amd64 tool
  local_action:
    module: copy
    src: "https://release-assets.githubusercontent.com/github-production-release-asset/168977645/e8ae4080-1eb1-11ea-996a-d379e524e717?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-09-05T05%3A39%3A14Z&rscd=attachment%3B+filename%3Dkerbrute_linux_386&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-09-05T04%3A38%3A40Z&ske=2025-09-05T05%3A39%3A14Z&sks=b&skv=2018-11-09&sig=GbqG%2FEOEZ1fT%2F1LrUn%2BAGPdbmSR%2FLX6%2B0neLdxTJcRo%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NzA0Nzg3NCwibmJmIjoxNzU3MDQ3NTc0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.XhFVjdQzLE1odQffsKOtyaZkwWux5l-UOymZYX8eTJo&response-content-disposition=attachment%3B%20filename%3Dkerbrute_linux_386&response-content-type=application%2Foctet-stream"
    dest: "/usr/local/bin/kerbrute_linux_amd64"
    mode: '0755'
  become: true
  become_method: sudo
