---
- name: Create directory for windows tools
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/tools/windows"
    state: directory

- name: Create directory for linux tools
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/tools/linux"
    state: directory

- name: Download LaZagne.exe and save to tools folder
  ansible.builtin.get_url:
    url: https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.7/LaZagne.exe
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/LaZagne.exe"
    mode: '0755'

- name: Download Snaffler.exe from official release
  ansible.builtin.uri:
    url: https://github.com/SnaffCon/Snaffler/releases/download/1.0.212/Snaffler.exe
    method: GET
    validate_certs: yes
    timeout: 60
    status_code: 304
    return_content: yes
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.3"
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/Snaffler.exe"

- name: Copy mimikatz.exe tools directory
  local_action:
    module: copy
    src: "/usr/share/windows-resources/mimikatz/x64/mimikatz.exe"
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/mimikatz.exe"
    mode: '0755'

- name: Copy mimipenguin tools directory
  local_action:
    module: copy
    src: "/usr/share/powershell-empire/empire/server/data/module_source/python/collection/mimipenguin.py"
    dest: "{{ ansible_user_dir }}/Documents/tools/linux/mimipenguin.py"
    mode: '0755'

- name: Download kerbrute
  local_action:
    module: get_url
    url: https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
    dest: /tmp/kerbrute_linux_amd64
    mode: '0755'

- name: Move kerbrute to system location
  become: true
  become_method: sudo
  copy:
    src: /tmp/kerbrute_linux_amd64
    dest: /usr/local/bin/kerbrute_linux_amd64
    mode: '0755'

- name: Copy nc.exe tools directory
  local_action:
    module: copy
    src: "/usr/share/windows-resources/binaries/nc.exe"
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/nc.exe"
    mode: '0755'

- name: Download chisel
  local_action:
    module: get_url
    url: https://github.com/jpillora/chisel/releases/download/v1.10.1/chisel_1.10.1_linux_amd64.gz
    dest: /tmp/chisel_1.7.7_linux_amd64.gz
    mode: '0755'

- name: Extract Chisel binary
  ansible.builtin.command:
    cmd: gzip -d chisel_1.7.7_linux_amd64.gz
    chdir: /tmp

- name: Move and rename Chisel to system location
  become: true
  become_method: sudo
  copy:
    src: /tmp/chisel_1.10.1_linux_amd64
    dest: /usr/local/bin/chisel
    mode: '0755'

