---
- name: Create directory for git tools
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/tools"
    state: directory

- name: Clone username-anarchy repository
  git:
    repo: https://github.com/urbanadventurer/username-anarchy
    dest: "{{ ansible_user_dir }}/tools/username-anarchy"

- name: Clone username-anarchy repository
  git:
    repo: https://github.com/AlessandroZ/LaZagne.git
    dest: "{{ ansible_user_dir }}/tools/LaZagne"

- name: Clone username-anarchy repository
  git:
    repo: https://github.com/unode/firefox_decrypt.git
    dest: "{{ ansible_user_dir }}/tools/firefox_decrypt"

- name: Clone PCredz repository
  git:
    repo: https://github.com/lgandx/PCredz.git
    dest: "{{ ansible_user_dir }}/tools/PCredz"

- name: Clone PowerHuntShares repository
  git:
    repo: https://github.com/NetSPI/PowerHuntShares.git
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/PowerHuntShares"

- name: Clone MANSPIDER repository
  git:
    repo: https://github.com/blacklanternsecurity/MANSPIDER.git
    dest: "{{ ansible_user_dir }}/tools/MANSPIDER"

- name: Clone Invoke-TheHash repository
  git:
    repo: https://github.com/Kevin-Robertson/Invoke-TheHash.git
    dest: "{{ ansible_user_dir }}/Documents/tools/windows/Invoke-TheHash"

- name: Clone KeyTabExtract repository
  git:
    repo: https://github.com/sosdave/KeyTabExtract.git
    dest: "{{ ansible_user_dir }}/tools/KeyTabExtract"
