---
- name: Build the PCredz docker image
  ansible.builtin.command:
    cmd: "docker build . -t pcredz"
    chdir: "{{ ansible_user_dir }}/tools/PCredz"

- name: Build the MANSPIDER docker image
  ansible.builtin.command:
    cmd: "docker build . -t manspider"
    chdir: "{{ ansible_user_dir }}/tools/MANSPIDER"
